version: 0.2
phases:
  build:
    commands:
      - sam build --use-container
      - sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --capabilities CAPABILITY_IAM --stack-name sam-app-praneeth-cb1 --resolve-s3 